# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180504_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_access_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
