# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_access_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
