# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-05 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180503_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('too_often', 'Too often')], default='new', max_length=9),
        ),
    ]
