# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180509_0836'),
        ('api', '0027_auto_20180503_1855'),
    ]

    operations = [
    ]
