# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_priority'),
        ('api', '0029_merge_20180509_1620'),
    ]

    operations = [
    ]
