# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20180510_1846'),
        ('api', '0028_check_department'),
    ]

    operations = [
    ]
