# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20180511_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='membership_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='check',
            name='priority_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
